seleniumFirefoxDriver_path: D:/seleniumFirefoxDriver/geckodriver
# ubuntu
# seleniumFirefoxDriver_path: /home/pabebe/seleniumFirefoxDriver/geckodriver
username: S1910W0783
web_password: zezuWANG927
home: 巨龙御园

rangle: (340, 301, 438, 328)
from_addr: zezuwang@qq.com
email_password: nohxgnlnvcembcch
to_addr: zezuwang@qq.com
smtp_server: smtp.qq.com